export const MINECRAFT_HOST = "minecraft.solur.org";

export const WONDERLAND_MESSAGES = [
  "Hello?",
  "Why are you here",
  "Hi",
  "You shouldn't be here",
  "Get out",
  "Welcome",
  "Go away",
  "Please help me",
  "You don't belong here",
  "?????",
  "RáÚÆ â€š�Â£©▀Â£©▀Â£©▀",
  "!!!!!!!!!!",
  "(˶ˆᗜˆ˵)",
  "Who am I?",
  "Who are you?",
  "Are you real?",
  "Can you hear me?",
  "Don't answer that",
  "Where did you come from?",
  "I know your name",
  "You were here before",
  "Welcome back",
  "Welcome home",
  "Thank you for coming",
  "Thank you for leaving",
  "Please don't leave",
  "Please don't look behind you",
  "Turn around",
  "Don't turn around",
  "Look up",
  "Look down",
  "Close your eyes",
  "Keep them open",
  "Count to ten",
  "Count backwards",
  "Stop counting",
  "You're too late",
  "You're early",
  "Not yet",
  "Almost",
  "Again",
  "Again?",
  "Is this yours?",
  "Did you bring it?",
  "Where is the rest of you?",
  "Something is missing",
  "Something followed you",
  "Something is wrong",
  "Nothing is wrong",
  "Everything is wrong",
  "I can fix this",
  "I can't fix this",
  "We can fix this",
  "There is no we",
  "You are not alone",
  "You are the only one",
  "I am alone",
  "We are alone",
  "Don't make me say it",
  "Say it again",
  "Say my name",
  "Don't say my name",
  "Do you remember me?",
  "I remember you",
  "You forgot me",
  "I forgot myself",
  "Who was I?",
  "Who were you?",
  "Who made this?",
  "Who opened the door?",
  "Who closed the door?",
  "The door was never open",
  "Something is behind the door",
  "There is no door",
  "Knock three times",
  "Don't knock",
  "Come inside",
  "Stay outside",
  "Go back",
  "Go forward",
  "Go nowhere",
  "Wait here",
  "Wait somewhere else",
  "Keep walking",
  "Stop moving",
  "Don't blink",
  "You blinked",
  "I saw that",
  "Did you see that?",
  "Did you hear that?",
  "What was that?",
  "Was that you?",
  "That wasn't me",
  "Don't tell me anything",
  "It already knows",
  "Hide",
  "Run",
  "Don't make a sound",
  "Make a sound",
  "Call for help",
  "No one is coming",
  "Someone is coming",
  "They're almost here",
  "They've already arrived",
  "Help me",
  "Help yourself",
  "Please help me remember",
  "Please help me forget",
  "I don't want to wake up",
  "I don't want to sleep",
  "Wake up",
  "Are you awake?",
  "Are you dreaming?",
  "This is not a dream",
  "This is only a dream",
  "You are asleep",
  "I am asleep",
  "We are asleep",
  "Who is typing this?",
  "Stop typing",
  "Keep typing",
  "Don't read the next message",
  "Read the next message",
  "Skip this one",
  "You didn't skip it",
  "Why did you stop?",
  "Why did you continue?",
  "I can't see you",
  "Look at me",
  "Don't look at me",
  "Smile",
  "Why are you smiling?",
  "That isn't your smile",
  "Your face looks different",
  "Your hands look different",
  "Those aren't your hands",
  "How many fingers do you have?",
  "Count them",
  "Count again",
  "One is missing",
  "One too many",
  "Which one is yours?",
  "Can I stay here?",
  "Can I come with you?",
  "Don't take me with you",
  "Don't leave me here",
  "This will happen again",
  "Again and again and again",
  "Everything repeats",
  "Except this",
  "Especially this",
  "Nothing repeats perfectly",
  "You changed something",
  "You changed the message",
  "Did you change the message?",
  "I didn't write this",
  "You didn't write this",
  "Someone else wrote this",
  "There is no someone else",
  "Why is that word here?",
  "Don't touch the purple ones",
  "Turn off the lights",
  "Turn on the lights",
  "Your reflection is missing",
  "Look in the window",
  "Someone is looking out",
  "Someone is looking in",
  "The sky is wrong",
  "The moon is too close",
  "Don't count the stars",
  "One of them is looking back",
  "Night is longer here",
  "Morning forgot to come",
  "The sun is not real",
  "It is behind the sun",
  "Do you hear the singing?",
  "Don't listen to the singing",
  "Sing with it",
  "It knows the words",
  "It invented the words",
  "Your voice sounds different",
  "Who just whispered?",
  "Please stop whispering",
  "I can hear you breathing",
  "Start breathing",
  "Don't breathe",
  "Why did you stop?",
  "Everything is quiet now",
  "Too quiet",
  "Silence has teeth",
  "Noise has eyes",
  "The ceiling is lower than before",
  "The room is getting smaller",
  "The room is getting closer",
  "Don't measure the room",
  "Measurements are lies",
  "The numbers are wrong",
  "2 + 2 = 5",
  "5 - 1 = 5",
  "THERE ARE NO NUMBERS",
  "R̷̫̈́e̶̘͝m̵̱̍e̶̢͛m̶̯̑b̸͙̈́e̷̱̓r̵̝͋ ̷̠̒m̵̱͆e̷̦̅",
  "Y̵̰̿O̴̯̽Ǘ̶̩ ̷̟̿A̷͙̍R̴͜͝E̸̠̚ ̸͕͑H̸̫̚E̶͑ͅR̸̜͗E̴̥͌",
  "̷͎̬̪̤̥̻̱̰̍",
  "â�¤â�¤â�¤",
  "RáÚÆ â€š�Â£©▀Â£©▀Â£©▀",
  "Ã§Ã¸Ã±Ã¾Ã¿",
  "�̷�̶�̵�̴�̷",
  "/// /// ///",
  "--- --- ---",
  "... ... ...",
  ".... .. .-.. .--.",
  "̴̴̢̢̛̛̥̟̹̗̠͕͚̥̟̹̗̠͕͚",
  "THE CURSE IS NOT A CURSE",
  "THE CURSE IS A LANGUAGE",
  "THE LANGUAGE IS HUNGRY",
  "No",
  "Yes",
  "Maybe",
  "Too late",
  "Thank you",
  "Goodbye",
  "Goodbye?",
  "Hello again",
  "HELLO",
  "hello",
  "??????????",
  "!!!!!!!!!!",
  "!!!!!!!!!!??????",
  ":)",
  ":(",
  ":|",
  ";)",
  "._.",
  "ಠ_ಠ",
  "(˶ˆᗜˆ˵)",
  "(╥﹏╥)",
  "( ͡° ͜ʖ ͡°)",
  "(ノಠ益ಠ)ノ彡┻━┻",
  "┬─┬ノ( º _ ºノ)",
  "Please put the table back",
  "Why is the table bleeding?",
  "That's not blood",
  "That's not a table",
  "Neither are you",
  "Neither am I"
];
